### ISSUE TITLE
install.makefile does not work on OSX

### ISSUE THREAD

**Issue by planemad** [WikimapsAtlas/WikimapsAtlas-generator#7]
Needs to be ported since it use apt-get

```
> make -f install.makefile

sudo apt-get -y install -y build-essential        #comment, is this needed ?
Password:
sudo: apt-get: command not found
make: *** [low_level] Error 1
```

**Comment by planemad** [comment]
Not sure what dependency i'm missing for this:

```
gdal_translate -co COMPRESS=JPEG -co PHOTOMETRIC=YCBCR ./color_reproj.tmp.tif ./color.gis.tif	# compress
Input file size is 1881, 1431
Warning 6: 'JPEG' is an unexpected value for COMPRESS creation option of type string-select.
0ERROR 1: Cannot create TIFF file due to missing codec for JPEG.
make[1]: *** [background_colors] Error 1
make: *** [topography] Error 2
```

**Comment by hugolpz** [comment]
Ok. [gdal_translate documentation](http://www.gdal.org/gdal_translate.html) confirms it's a valid value.
@planemad : Do you have imagemagick on your computer ? I do. It may help.
Next step : create early an issue on http://gis.stackexchange.com/questions/ , as answers come in 3 to 7 days.

**Comment by jaakla** [comment]
I got this resolved by re-installing whole GDAL framework. Tried first reinstalling UnixImageIO but this was not enough.
